# Generated by Django 6.0.6 on 2026-06-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('lu', models.BooleanField(default=False)),
                ('lu_at', models.DateTimeField(blank=True, null=True)),
                ('est_modifie', models.BooleanField(default=False)),
                ('est_supprime', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PieceJointe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_fichier', models.CharField(max_length=255)),
                ('url_fichier', models.CharField(max_length=500)),
                ('type_fichier', models.CharField(blank=True, max_length=50, null=True)),
                ('taille', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'piece_jointe',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ReactionMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'reaction_message',
                'managed': False,
            },
        ),
    ]
