# Generated by Django 6.0.6 on 2026-06-10 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('offre', 'Offre'), ('demande', 'Demande')], max_length=10)),
                ('format', models.CharField(choices=[('presentiel', 'Présentiel'), ('en_ligne', 'En ligne'), ('les_deux', 'Les deux')], default='les_deux', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('active', 'Active'), ('archivee', 'Archivée'), ('fermee', 'Fermée')], default='active', max_length=10)),
                ('places_max', models.IntegerField(default=1)),
                ('places_restantes', models.IntegerField(default=1)),
                ('likes', models.IntegerField(default=0)),
                ('vues', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'annonce',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Matiere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('categorie', models.CharField(blank=True, max_length=100, null=True)),
                ('filiere_cible', models.CharField(blank=True, max_length=100, null=True)),
                ('icone', models.CharField(default='school', max_length=50)),
                ('couleur', models.CharField(default='#386943', max_length=20)),
            ],
            options={
                'db_table': 'matiere',
                'managed': False,
            },
        ),
    ]
